### ISSUE TITLE
Is this all JS based on PHP involved?

### ISSUE THREAD

**Issue by halukkaramete** [classy-org/classy-org-wp#9]
Hello,

I'm running a cached wordpress site. I cache all WP output into HTML and serve the site without loading the wp-blog-header. Anyway. I run into your github ref. Could you pls tell me if your code would run on  a cached site? 

It would, if your shortcode simply generates a specific JS code ( just like google analytics )? 
Is that how it is? Or is there an interaction taking place to your servers at the time of PHP is running kind of like authorize net style?

**Comment by cj-beck** [comment]
Hi,
If I understand your question correctly--yes, this should work with a WP site that employs caching.  That said, some caching is built into the plugin, so you could end up with the double-cache problem where your pages are more out-of-date than you expect, but it all should still function correctly.

The plugin doesn't produce javascript, so that should not be an issue.
